/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/Desk.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Desk.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube004.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Cube004_1.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Cube004_2.geometry} material={materials['Material.003']} />
      <mesh geometry={nodes.Cube004_3.geometry} material={materials['Material.004']} />
    </group>
  )
}

useGLTF.preload('/Desk.glb')
