/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/Arid_19_11.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Arid_19_11(props) {
  const { nodes, materials } = useGLTF('./models/Arid_19_11.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.arid_island_19_11.geometry} material={materials['Material.003']} position={[0,21.9,0]}/>
    </group>
  )
}

useGLTF.preload('./models/Arid_19_11.glb')
