/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/Multiplayer.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function MultiplayerIsland(props) {
  const { nodes, materials } = useGLTF('./models/Multiplayer.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.island_43_multiplayer_base.geometry} material={materials['Material.001']} />
    </group>
  )
}

useGLTF.preload('./models/Multiplayer.glb')
