/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/Ship2.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Ship2(props) {
  const { nodes, materials } = useGLTF('./models/Ship2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Ship2.geometry} material={materials['Material.001']}  position={props.position}/>
    </group>
  )
}

useGLTF.preload('./models/Ship2.glb')
