/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/Stormworks_Moon.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Moon(props) {
  const { nodes, materials } = useGLTF('./models/Stormworks_Moon.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.moon.geometry} material={materials['Material.001']} scale={20} position={[-350,3200,0]}/>
    </group>
  )
}

useGLTF.preload('./models/Stormworks_Moon.glb')
